[build]
    command = "npm run build"
    publish = "dist"
[[redirects]]
  from = "/"
  to = "/pl"
  status = 302
  conditions = {Language = ["pl"]}
[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  conditions = {Language = ["en"]}
[dev]
    targetPort = 8000